function(find_file_from_mingw _FILENAME _RESULT)
    set(USER_PATHS $ENV{PATH})
    string(REPLACE ";" ";" USER_PATHS "${USER_PATHS}")
    list(TRANSFORM USER_PATHS REPLACE "\\\\" "/")

    foreach(_PATH ${USER_PATHS})
        find_file(FOUND_FILE "${_FILENAME}" PATHS "${_PATH}" NO_DEFAULT_PATH)
        if(FOUND_FILE)
            find_file(FOUND_GCC "gcc.exe" PATHS "${_PATH}" NO_DEFAULT_PATH)
            find_file(FOUND_GPP "g++.exe" PATHS "${_PATH}" NO_DEFAULT_PATH)
            if(FOUND_GCC AND FOUND_GPP)
                set(${_RESULT} "${FOUND_FILE}" PARENT_SCOPE)
                return()
            endif()
        endif()
    endforeach()
    
    set(${_RESULT} "" PARENT_SCOPE)
endfunction()
